### ISSUE TITLE
Frontend code repos not publicly available

### ISSUE THREAD

**Issue by ivanistheone** [cassproject/CASS#186]
When trying to get clone the repo following the local dev instructions, I noticed the git submodules cannot be accessed:

```
> git submodule update --init --recursive

fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.

Failed to clone 'src/main/webapp/cass-align'. Retry scheduled
Failed to clone 'src/main/webapp/cass-editor'. Retry scheduled
Failed to clone 'src/main/webapp/cass-gap-analysis'. Retry scheduled
Failed to clone 'src/main/webapp/cass-profile'. Retry scheduled
Failed to clone 'src/main/webapp/cass-viewer'. Retry scheduled
Failed to clone 'src/main/webapp/cass-vlrc'. Retry scheduled
Failed to clone 'src/main/webapp/cass-align' a second time, aborting
```

**Comment by ivanistheone** [comment]
Workaround: 
  1. comment out lines 17 through 19 in the docker-compose file https://github.com/cassproject/CASS/blob/master/docker-compose.yml#L17-L19
  2. and replace them with
     ```
     image: cassproject/cass
     ```
     to use the pre-build docker image which has all the frontend code baked into it.

**Comment by Lomilar** [comment]
Hey, I think another workaround is, when cloning, to use --recurse-submodules

We use relative paths in the .gitmodules due to this git project constellation being hosted in multiple locations (some public, some private) and it looks like that may be what you ran into.

I'll work on something practical to help resolve this and drop it into the readme. Thanks!

**Comment by ivanistheone** [comment]
> We use relative paths in the .gitmodules

Oh I see.  I can confirm changing the rel-paths to point to the  `cassproject/` repos worked.
